# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- build
- test
- deploy
#- review
#- dast
#- staging
#- canary
#- production
#- incremental rollout 10%
#- incremental rollout 25%
#- incremental rollout 50%
#- incremental rollout 100%
#- performance
#- cleanup
#sast:
  #stage: test
#include:
#- template: Auto-DevOps.gitlab-ci.yml
#image: node

build:
  variables:
    MODULE_NAME: "pehu-app"
    MODULE_VER: "0.1.1"
  before_script:
    - ln -s /usr/lib/node_modules .
    - mkdir -p build
  
  stage: build
  script:
    - echo '{"type":"module"}' > package.json
    - qunit src/www/tests/*.js
    - rm package.json
    - npx webpack --config src/www/webpack.config.cjs
    - cp build/bundle.js /tmp/${MODULE_NAME}_bundle.js

  #artifacts:
   # when: on_success
    #paths:
    #  - build

test:
  stage: test
  script:
    - echo test
    - cd src/www/tests/cypress    
    - npx cypress run --config-file cypress.config.cjs

deploy:
  variables:
    MODULE_NAME: "pehu-app"
    MODULE_VER: "0.1.1"
  before_script:
    - mkdir -p build
  stage: deploy
  script:
  # package building
    - cd build
    - cp /tmp/${MODULE_NAME}_bundle.js bundle.js
    - cmake ..
    - make package

  # salt env configuration
    - /srv/salt/deploy/generate_state.sh ${MODULE_NAME} ${MODULE_VER} > /srv/salt/deploy/${MODULE_NAME}.sls
    - cp ${MODULE_NAME}-${MODULE_VER}-Linux.deb /srv/salt/deploy/packages

  # push deployment code on the minion
    - salt  'pokou' state.apply deploy.${MODULE_NAME}
